### PR TITLE
Fix eager API thunk retention

### LINKED ISSUE #248: "Error in eager listener: KeyError: key 578 not found"
I have written a toy code to experiment with Dagger.jl: [WaveToyDagger.jl](https://github.com/eschnett/WaveToyDagger.jl). This solves the scalar wave equation (computationally similar to the diffusion equation) on a 2D array, split into blocks, and parallelized via Dagger.jl.

When I run the code, I receive the error
```
Error in eager scheduler:
KeyError: key 133 not found
```
It looks as if this was a problem in Dagger.jl (of course I cannot be sure).

The complete backtrace is
```
julia> using WaveToyDagger
[ Info: Precompiling WaveToyDagger [1ebf5abb-aa52-4892-b9b8-f6b456a24862]

julia> WaveToyDagger.main()
Error in eager scheduler:
KeyError: key 133 not found
Stacktrace:
 [1] getindex(h::Dict{Int64, Any}, key::Int64)
   @ Base ./dict.jl:482
 [2] compute_dag(ctx::Dagger.Context, d::Dagger.Thunk; options::Dagger.Sch.SchedulerOptions)
   @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/Sch.jl:417
 [3] compute(ctx::Dagger.Context, d::Dagger.Thunk; options::Dagger.Sch.SchedulerOptions)
   @ Dagger ~/.julia/packages/Dagger/Pb5aU/src/compute.jl:31
 [4] (::Dagger.Sch.var"#43#44"{Dagger.Context})()
   @ Dagger.Sch ./task.jl:411
Error in eager listener:
KeyError: key 578 not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:482 [inlined]
  [2] (::Dagger.Sch.var"#39#40"{Dagger.Sch.ComputeState})(arg::Dagger.Sch.ThunkID)
    @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:162
  [3] map
    @ ./tuple.jl:215 [inlined]
  [4] _add_thunk!(ctx::Dagger.Context, state::Dagger.Sch.ComputeState, task::Task, tid::Int64, ::Tuple{typeof(WaveToyDagger.get_ghosts), Tuple{Dagger.Sch.ThunkID, Int64, Int64}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dagger.ThunkFuture})
    @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:162
  [5] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [6] invokelatest
    @ ./essentials.jl:706 [inlined]
  [7] #21
    @ ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:61 [inlined]
  [8] lock(f::Dagger.Sch.var"#21#25"{Tuple{typeof(WaveToyDagger.get_ghosts), Tuple{Dagger.Sch.ThunkID, Int64, Int64}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dagger.ThunkFuture}, typeof(Dagger.Sch._add_thunk!), Dagger.Context, Dagger.Sch.ComputeState, Task}, l::ReentrantLock)
    @ Base ./lock.jl:187
  [9] macro expansion
    @ ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:60 [inlined]
 [10] (::Dagger.Sch.var"#20#24"{Dagger.Context, Dagger.Sch.ComputeState, Task, Distributed.RemoteChannel{Channel{Any}}, Distributed.RemoteChannel{Channel{Any}}})()
    @ Dagger.Sch ./task.jl:411
Stacktrace:
 [1] exec!(::Function, ::Dagger.Sch.SchedulerHandle, ::Function, ::Vararg{Any, N} where N)
   @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:98
 [2] add_thunk!(::Function, ::Dagger.Sch.SchedulerHandle, ::Dagger.Sch.ThunkID, ::Vararg{Any, N} where N; future::Dagger.ThunkFuture, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/dynamic.jl:159
 [3] eager_thunk()
   @ Dagger.Sch ~/.julia/packages/Dagger/Pb5aU/src/sch/eager.jl:81
 [4] macro expansion
   @ ~/.julia/packages/Dagger/Pb5aU/src/processor.jl:154 [inlined]
 [5] (::Dagger.var"#51#52"{typeof(Dagger.Sch.eager_thunk), Tuple{}, NamedTuple{(:sch_uid, :sch_handle, :processor, :utilization), Tuple{UInt64, Dagger.Sch.SchedulerHandle, Dagger.ThreadProc, UInt64}}})()
   @ Dagger ./threadingconstructs.jl:169
^CERROR: InterruptException:
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:710
  [2] wait
    @ ./task.jl:769 [inlined]
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base ./condition.jl:106
  [4] wait(e::Base.Event)
    @ Base ./lock.jl:340
  [5] _spawn(::Function, ::Dagger.EagerThunk, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Dagger ~/.julia/packages/Dagger/Pb5aU/src/thunk.jl:206
  [6] _spawn(::Function, ::Dagger.EagerThunk, ::Vararg{Any, N} where N)
    @ Dagger ~/.julia/packages/Dagger/Pb5aU/src/thunk.jl:200
  [7] spawn(::Function, ::Dagger.EagerThunk, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Dagger ~/.julia/packages/Dagger/Pb5aU/src/thunk.jl:217
  [8] spawn
    @ ~/.julia/packages/Dagger/Pb5aU/src/thunk.jl:216 [inlined]
  [9] exchange_ghosts(domain::WaveToyDagger.Domain{StaticArrays.SVector{4, Float64}})
    @ WaveToyDagger ~/src/jl/WaveToyDagger.jl/src/WaveToyDagger.jl:178
 [10] rhs′
    @ ~/src/jl/WaveToyDagger.jl/src/WaveToyDagger.jl:206 [inlined]
 [11] rk2(f::typeof(WaveToyDagger.rhs′), u::WaveToyDagger.Domain{StaticArrays.SVector{4, Float64}}, h::Float64)
    @ WaveToyDagger ~/src/jl/WaveToyDagger.jl/src/WaveToyDagger.jl:212
 [12] main()
    @ WaveToyDagger ~/src/jl/WaveToyDagger.jl/src/WaveToyDagger.jl:226
 [13] top-level scope
    @ REPL[2]:1

julia>
```

The line in my code that last calls Dagger.jl before this error is https://github.com/eschnett/WaveToyDagger.jl/blob/cd66c4c9f761c63c1fef3e0c1c3276cdc1ac7afb/src/WaveToyDagger.jl#L178. This spawns a call to my function `get_ghosts`, with an `EagerChunk` as argument.

I'm using the struct `Future{T}` to attach an (expected) return type to chunks; this helps me debug.

When I uncomment [line 10](https://github.com/eschnett/WaveToyDagger.jl/blob/cd66c4c9f761c63c1fef3e0c1c3276cdc1ac7afb/src/WaveToyDagger.jl#L10) in my code, all chunks are fetched right after they are created, serializing the code. When I do this, the error goes away.

Any pointer towards debugging this would be appreciated. I apologize for dumping my complete code onto you.

### PR DESCRIPTION
**Pull request by jpsamaroo**
Should fix #248

### CODE REVIEW

**Comment by jpsamaroo** [comment]
One thing to note about this PR is that, while `EagerThunk` and `ThunkID` references will now properly preserve their associated `Thunk` object, there will be a rather large increase in `DRef`s (distributed references), and so distributed GC traffic will definitely increase and start to become a bottleneck. I expect we'll have to find some way to optimize GC traffic transfers in MemPool to accomodate this.

**Comment by jpsamaroo** [comment]
While I fix up the tests, @eschnett would you mind testing this locally to make sure it works for you?

**Comment by eschnett** [comment]
I'd be happy to! Just let me know when and which branch to test.

I just tested the `jps/wavetoy-fix` branch. It errors with
```
     Testing Running tests...
Error in eager listener:
AssertionError: t !== nothing
Stacktrace:
  [1] unwrap_weak_checked
    @ ~/.julia/packages/Dagger/kzwoA/src/thunk.jl:151 [inlined]
  [2] _broadcast_getindex_evalf
    @ ./broadcast.jl:648 [inlined]
  [3] _broadcast_getindex
    @ ./broadcast.jl:621 [inlined]
  [4] #19
    @ ./broadcast.jl:1098 [inlined]
  [5] macro expansion
    @ ./ntuple.jl:74 [inlined]
  [6] ntuple
    @ ./ntuple.jl:69 [inlined]
  [7] copy(bc::Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, typeof(Dagger.unwrap_weak_checked), Tuple{NTuple{5, Dagger.WeakThunk}}})
    @ Base.Broadcast ./broadcast.jl:1098
  [8] materialize
    @ ./broadcast.jl:883 [inlined]
  [9] (::Dagger.Sch.var"#dominates#34")(target::Dagger.Thunk, t::Dagger.Thunk)
    @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:138
 [10] (::Dagger.Sch.var"#32#35"{Dagger.Thunk})(_t::Dagger.Thunk)
    @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:138
 [11] _any(f::Dagger.Sch.var"#32#35"{Dagger.Thunk}, itr::Tuple{Dagger.Thunk}, #unused#::Colon)
    @ Base ./reduce.jl:876
 [12] any(f::Function, itr::Tuple{Dagger.Thunk})
    @ Base ./reduce.jl:871
 [13] (::Dagger.Sch.var"#dominates#34")(target::Dagger.Thunk, t::Dagger.Thunk)
    @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:138
 [14] _register_future!(ctx::Dagger.Context, state::Dagger.Sch.ComputeState, task::Task, tid::Int64, ::Tuple{Dagger.ThunkFuture, Dagger.Sch.ThunkID})
    @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:139
 [15] _add_thunk!(ctx::Dagger.Context, state::Dagger.Sch.ComputeState, task::Task, tid::Int64, ::Tuple{typeof(*), Tuple{Float64, Dagger.Sch.ThunkID}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dagger.ThunkFuture, MemPool.DRef})
    @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:190
 [16] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [17] invokelatest
    @ ./essentials.jl:706 [inlined]
 [18] #23
    @ ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:69 [inlined]
 [19] lock(f::Dagger.Sch.var"#23#27"{Tuple{typeof(*), Tuple{Float64, Dagger.Sch.ThunkID}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dagger.ThunkFuture, MemPool.DRef}, typeof(Dagger.Sch._add_thunk!), Dagger.Context, Dagger.Sch.ComputeState, Task}, l::ReentrantLock)
    @ Base ./lock.jl:187
 [20] macro expansion
    @ ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:68 [inlined]
 [21] (::Dagger.Sch.var"#22#26"{Dagger.Context, Dagger.Sch.ComputeState, Task, Distributed.RemoteChannel{Channel{Any}}, Distributed.RemoteChannel{Channel{Any}}})()
    @ Dagger.Sch ./task.jl:411
Stacktrace:
 [1] exec!(::Function, ::Dagger.Sch.SchedulerHandle, ::Function, ::Vararg{Any, N} where N)
   @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:112
 [2] add_thunk!(::Function, ::Dagger.Sch.SchedulerHandle, ::Float64, ::Vararg{Any, N} where N; future::Dagger.ThunkFuture, ref::MemPool.DRef, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/dynamic.jl:177
 [3] eager_thunk()
   @ Dagger.Sch ~/.julia/packages/Dagger/kzwoA/src/sch/eager.jl:81
 [4] macro expansion
   @ ~/.julia/packages/Dagger/kzwoA/src/processor.jl:154 [inlined]
 [5] (::Dagger.var"#51#52"{typeof(Dagger.Sch.eager_thunk), Tuple{}, NamedTuple{(:sch_uid, :sch_handle, :processor, :utilization), Tuple{UInt64, Dagger.Sch.SchedulerHandle, Dagger.ThreadProc, UInt64}}})()
   @ Dagger ./threadingconstructs.jl:169
```

**Comment by jpsamaroo** [comment]
Crap, okay, I had it working at one point, but must have messed it back up along the way. Thankfully I can reproduce the failure locally.

**Comment by jpsamaroo** [comment]
Actually, no, this failure is (probably) a red herring. Background: `dominates` is a function that walks the whole DAG upstream (along the inputs) of a given task, and wants to verify that we don't encounter our own task during the process, so that we can safely wait on the task of interest; if we encounter ourselves, then we would have a cycle in the DAG, and that is illegal (and would cause an infinite hang).

In this case, we can just ignore any tasks that have expired (currently those caught by the assertion), since if our own task is currently executing, it will not have expired; I wouldn't be surprised if later on I find that I'm wrong about this assumption, but I think it's a fair compromise for now.

**Comment by jpsamaroo** [comment]
@eschnett WayeToyDagger works locally for me with the current changes, and with CI passing, I'm ready to merge this whenever. If you want to test one last time, please go ahead and let me know if it's working for you!

Also, if you end up registering this or a similar package, I'd be happy to include it as part of the tests so we don't break your code again!

**Comment by eschnett** [comment]
Yes, I confirm it works.

**Pull request merged**
