### PR TITLE
 Don't set finalizers for DRef chunks as they are already set in MemPool

### PR DESCRIPTION
**Pull request by nkottary**

### CODE REVIEW

**Comment by shashi** [comment]
Actually can't we just add this to serialize deserialize of DRef?? I think that's more correct, we can just delete any finalizer code on Chunks

**Comment by nkottary** [comment]
I've added `deserialize` to MemPool: https://github.com/JuliaComputing/MemPool.jl/pull/28

but I get a `StackOverflowError` now.

**Comment by shashi** [comment]
What's a minimal example?

**Comment by shashi** [comment]
fixed it

**Comment by jpsamaroo** [comment]
Closing since the DRef is now refcounted.

**Pull request closed without merging**
