### PR TITLE
Fix the deployment of the documentation

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @jpsamaroo

### CODE REVIEW

**Comment by DilumAluthge** [comment]
The Coveralls failure is not relevant.

**Comment by DilumAluthge** [comment]
@jpsamaroo This is ready to review and merge.

**Comment by jpsamaroo** [comment]
The link in the README's `docs-master-url` badge is also wrong (my fault, I copied from a JuliaGPU README). Would you mind correcting that? Should just be `s/juliagpu/juliaparallel/`.

**Comment by DilumAluthge** [comment]
> The link in the README's `docs-master-url` badge is also wrong (my fault, I copied from a JuliaGPU README). Would you mind correcting that? Should just be `s/juliagpu/juliaparallel/`.

Done!

**Pull request merged**
