### PR TITLE
Force reschedule in adjust_pressure!

### LINKED ISSUE #282: Hang #1 in Eager API usage
Starting the effort of documenting any somewhat replicable hangs

Observations/conditions:
1. Can be ctrl-c'd - stacktrace below (other's not so much)
2. Some Julia instances will hang almost immediately (1st or 2nd run of groupy), others will never hang no matter how many runs (consistent with other hangs)
3. Julia master with all available fixes merged and Dagger with all available fixes merged

Thread usage during the hang : none
image

Stacktrace:

```
PS C:\Users\krynjupc\.julia\dev\Dagger> julia -t16
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.490 (2021-09-13)
 _/ |\__'_|_|_|\__'_|  |  kr/distributed-ref-count-race/dfd4724ce3 (fork: 2 commits, 8 days)
|__/                   |

(@v1.8) pkg> activate .
  Activating project at `C:\Users\krynjupc\.julia\dev\Dagger`

julia> using Dagger, DataFrames, Arrow, OnlineStats

julia> d = DTable(Arrow.Table, "data/".*readdir("data"))
DTable with 100 partitions
Tabletype: unknown (use `tabletype!(::DTable)`)

julia> g = Dagger.groupby(d, x->round(x.a, digits=1));
ERROR: InterruptException:
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base .\task.jl:764
  [2] wait()
    @ Base .\task.jl:824
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base .\condition.jl:112
  [4] fetch_buffered(c::Channel{Any})
    @ Base .\channels.jl:366
  [5] fetch(c::Channel{Any})
    @ Base .\channels.jl:360
  [6] fetch_ref(::Distributed.RRID)
    @ Distributed C:\cygwin64\home\krynjupc\julia\usr\share\julia\stdlib\v1.8\Distributed\src\remotecall.jl:593
  [7] call_on_owner
    @ C:\cygwin64\home\krynjupc\julia\usr\share\julia\stdlib\v1.8\Distributed\src\remotecall.jl:546 [inlined]
  [8] fetch(r::Distributed.Future)
    @ Distributed C:\cygwin64\home\krynjupc\julia\usr\share\julia\stdlib\v1.8\Distributed\src\remotecall.jl:587
  [9] (::Dagger.var"#73#74"{OSProc, Dagger.ThunkFuture})()
    @ Dagger C:\Users\krynjupc\.julia\dev\Dagger\src\thunk.jl:132
 [10] thunk_yield(f::Dagger.var"#73#74"{OSProc, Dagger.ThunkFuture})
    @ Dagger.Sch C:\Users\krynjupc\.julia\dev\Dagger\src\sch\eager.jl:63
 [11] fetch(t::Dagger.ThunkFuture; proc::OSProc)
    @ Dagger C:\Users\krynjupc\.julia\dev\Dagger\src\thunk.jl:131
 [12] fetch
    @ C:\Users\krynjupc\.julia\dev\Dagger\src\thunk.jl:131 [inlined]
 [13] fetch(t::Dagger.EagerThunk)
    @ Dagger C:\Users\krynjupc\.julia\dev\Dagger\src\thunk.jl:193
 [14] groupby(d::DTable, f::Function; merge::Bool, chunksize::Int64)
    @ Dagger C:\Users\krynjupc\.julia\dev\Dagger\src\table\groupby.jl:70
 [15] groupby(d::DTable, f::Function)
    @ Dagger C:\Users\krynjupc\.julia\dev\Dagger\src\table\groupby.jl:57
 [16] top-level scope
    @ REPL[4]:1
```

### PR DESCRIPTION
**Pull request by jpsamaroo**
(Hopefully) fixes #282 

Thanks to @krynju for narrowing this one down!

### CODE REVIEW

**Comment by krynju** [comment]
So here the latest status is that against all logic this piece below in `_adjust_pressure!` fixes the issue for the single threaded example:

```julia
if pressure > 0
        put!(state.chan, RescheduleSignal())
end
```

**Comment by krynju** [comment]
@jpsamaroo  new findings based on this example
```
using Dagger
f = (x) -> 10 + x
g = (x) -> fetch(Dagger.spawn(f, x))
fetch(Dagger.spawn(g, 10))
```

so the state at which the thing hangs is that:
- `g` is in running, waits for ThunkFuture of f
- `f`, future is registered properly, but gets stuck in scheduler, when you ctrl-c it's in `state.ready` and the place it gets put in `state.ready`, which i tracked down, is here https://github.com/JuliaParallel/Dagger.jl/blob/jps/adjust-pressure-reschedule/src/sch/Sch.jl#L682

now i don't have any idea why does it land in `failed_scheduling`? maybe by that time the worker is still fully occupied with the pressure from `g`? or maybe it should get scheduled again after this fail?

btw not using the put! reschedule signal in adjust pressure for this investigation

**Comment by krynju** [comment]
Ok looked into it more, I see nothing weird about it, it's just stuck here: https://github.com/JuliaParallel/Dagger.jl/blob/19d9bd5577c95e199960f2bc4108e36d389ad9aa/src/sch/Sch.jl#L401

The below works fine for me, the condition on notify(TASK_SYNC) breaks things.
I assume it's due to the fact that adjusting pressure both ways somewhat means a task has finished, not necessairly the same task though

```julia
"Adjusts the scheduler's cached pressure indicator for the specified worker by
the specified amount."
function adjust_pressure!(h::SchedulerHandle, proctype::Type, pressure)
    uid = Dagger.get_tls().sch_uid
    lock(TASK_SYNC) do
        PROC_UTILIZATION[uid][proctype][] += pressure
        notify(TASK_SYNC)
    end
    exec!(_adjust_pressure!, h, myid(), proctype, pressure)
end
function _adjust_pressure!(ctx, state, task, tid, (pid, proctype, pressure))
    state.worker_pressure[pid][proctype] += pressure
    pressure < 0 && put!(state.chan, RescheduleSignal())
    nothing
end
```

**Comment by jpsamaroo** [comment]
Being stuck on `take!` probably means that we need to put a `RescheduleSignal`.

> now i don't have any idea why does it land in `failed_scheduling`?

Yeah `failed_scheduling` is fully related to pressure; you only end up there if at capacity on all workers.

**Comment by krynju** [comment]
> Being stuck on `take!` probably means that we need to put a `RescheduleSignal`.

So I guess the question is whether adjust_pressure is the optimal place to put that RescheduleSignal.
On the way to figure out what's the issue I haven't really found a better place. This seems to be the moment to do that

**Pull request merged**
