### PR TITLE
Stop tracking the manifest files

### PR DESCRIPTION
**Pull request by JamesWrigley**
I don't think these really need to be tracked, and they cause conflicts whenever the manifest is changed and you switch branch or something.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
This generally LGTM - do you know why the docs build is failing? Maybe the default settings changed upstream? We need to be able to skip some of these missing doc checks until we get that fully fixed up.

**Comment by JamesWrigley** [comment]
Ahh yes, that'll be because #482 is fixed now that ProfileSVG.jl has been updated, so now the docs will be using Documenter.jl v1 which has stricter defaults. I'll update the docs :)

**Comment by JamesWrigley** [comment]
Fixed in 518a4b0 and 85df3cb, so this should fix #482 too now.

**Comment by JamesWrigley** [comment]
A bunch of other jobs are still broken, but I don't that's caused by the manifest being deleted, and it should be working in #463, sooooo I don't think I'll bother fixing that :see_no_evil:

**Comment by jpsamaroo** [comment]
Thanks!

Yes those jobs were previously failing, but I haven't had the chance to look into them.

**Pull request merged**
