### PR TITLE
toward full documentation

### PR DESCRIPTION
**Pull request by ExpandingMan**
I have expanded the documentation a little to get this package on the road to having good, reliable docs.  Mainly what I have done here is add an API section to the doc that lists documented types, functions and macros in the package.  I tried to model what I did off of DataFrames.jl which has particularly complete and excellent documentation.

Note that I have added *very little* to the actual content of the documentation.  I did this when going through the package a bit to see how it works, but I am certainly not a regular contributor to this package so my knowledge of its internals is quite poor.

Hopefully, this can serve as a starting point to make it easier for more knowledgeable contributors to make more complete docs.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I removed some internal functions from the list, and added others that I consider important to configuring Dagger. I'll add some more internal scheduler functions to the list once I've added some safer functions for modifying the internal scheduler state.

**Comment by jpsamaroo** [comment]
Windows support is somewhat unreliable for more advanced functionality; 1 or 2 passing CI jobs is usually sufficient.

**Comment by ExpandingMan** [comment]
Is it just me or is github CI/CD only running tests of JuliaDB and not Dagger itself?  If so, can we add tests for Dagger?  (No need to do it in this PR of course)

**Comment by jpsamaroo** [comment]
We should have Buildkite, but for some reason it's not running; @DilumAluthge do you know what's going on with that?

**Comment by Moelf** [comment]
nice! while we're on the subject, can we get a more useful `README` than `]add .. using..`?

**Comment by ExpandingMan** [comment]
That's kind of redundant with the docs no?  What did you have in mind?

**Comment by jpsamaroo** [comment]
I think it's fine to add a simple example, but anything beyond that is definitely for the docs. I personally am not a fan of the prevailing wisdom to have literally nothing useful other than a docs link in the README.

**Comment by jpsamaroo** [comment]
Thanks a bunch @ExpandingMan !

**Comment by DilumAluthge** [comment]
Not sure why Buildkite isn't running. I'll look into it.

**Pull request merged**
