### PR TITLE
Remove context from move

### LINKED ISSUE #143: Creation of new Contexts makes it unsafe to add new workers during ongoing job
I ran into this when using ClusterManagers and starting the job before all workers where started. This is useful because when the cluster is loaded the time between first worker and last can be very long.

MWE
```julia
julia> using Distributed

julia>ps1 = addprocs(2, exeflags="--project");

julia> @everywhere begin
       using Dagger, Distributed
       # Condition to guarantee that processing is not completed before we add new workers
       c = Condition()
       function testfun(i)
           i < 5 && return i
           wait(c)
           return i
       end
       end

julia> ts = delayed(vcat)((delayed(testfun)(i) for i in 1:10)...);

julia> job = @async collect(ts);

julia> addprocs(2, exeflags="--project");

julia> while !istaskdone(job)
       @everywhere ps1 notify(c)
       end

julia> fetch(job)
ERROR: TaskFailedException:
On worker 3:
KeyError: key Dagger [d58978e5-989f-55fb-8d15-ea34adc7bf54] not found
getindex at .\dict.jl:467 [inlined]
root_module at .\loading.jl:968 [inlined]
deserialize_module at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:953
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:855
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:773
deserialize_datatype at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:1251
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:826
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:773
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:833
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Serialization\src\Serialization.jl:773 [inlined]
deserialize_msg at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\messages.jl:99
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
message_handler_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\process_messages.jl:185
process_tcp_streams at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\process_messages.jl:142
#99 at .\task.jl:356
remotecall_fetch(::Function, ::Distributed.Worker, ::Context, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\remotecall.jl:394
remotecall_fetch(::Function, ::Distributed.Worker, ::Context, ::Vararg{Any,N} where N) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\remotecall.jl:386
remotecall_fetch(::Function, ::Int64, ::Context, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\remotecall.jl:421
remotecall_fetch at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\remotecall.jl:421 [inlined]
macro expansion at \.julia\packages\Dagger\4Yyj2\src\scheduler.jl:366 [inlined]
(::Dagger.Sch.var"#30#31"{Context,OSProc,Int64,typeof(vcat),NTuple{10,Dagger.Chunk{Any,MemPool.DRef,Dagger.ThreadProc}},Channel{Any},Bool,Bool,Bool,Dagger.Sch.ThunkOptions,NTuple{10,Int64}})() at .\task.jl:356
Stacktrace:
 [1] compute_dag(::Context, ::Thunk; options::Nothing) at \.julia\packages\Dagger\4Yyj2\src\scheduler.jl:137
 [2] compute(::Context, ::Thunk; options::Nothing) at \.julia\packages\Dagger\4Yyj2\src\compute.jl:32
 [3] collect(::Context, ::Thunk; options::Nothing) at \.julia\packages\Dagger\4Yyj2\src\compute.jl:8
 [4] #collect#73 at \.julia\packages\Dagger\4Yyj2\src\compute.jl:10 [inlined]
 [5] collect(::Thunk) at \.julia\packages\Dagger\4Yyj2\src\compute.jl:10
 [6] (::var"#15#16")() at .\task.jl:356
Stacktrace:
 [1] wait at .\task.jl:267 [inlined]
 [2] fetch(::Task) at .\task.jl:282
 [3] top-level scope at REPL[27]:1
 [4] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1088
```

### PR DESCRIPTION
**Pull request by DrChainsaw**
Fixes #143 
Avoids creation of a new context

If there is a good reason to not pass the context (IC bandwidth?) then perhaps initialize it with myid?

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Is there any chance you can add a test that this PR makes pass?

**Comment by DrChainsaw** [comment]
Ah yes of course! Lazy github edit. Will push soon!

**Comment by jpsamaroo** [comment]
So I would like to merge this, but I am concerned about serializing `ctx.procs`, which is increasingly acquiring more data (and will continue to do so). Since all elements in `ctx.procs` should be of type `OSProc`, if you could manually send just the `pid` field from each processor and do `OSProc(pid)` for each processor on the remote end, that would be much more efficient and would be equally correct (since I've made it such that `OSProc(pid)` should always be a valid thing to do on any process). You can probably send `log_sink`, `profile`, and `options` as-is (if it becomes a problem, we can fix that later).

**Comment by DrChainsaw** [comment]
Sure thing! Btw, I don't see the context ever being used in any implementation of move. Can it be removed?

**Comment by DrChainsaw** [comment]
Another option is to not pass the context and just create it from `myid` on the other side. 

The exception is only thrown because `Context()` creates OSProcs of all `procs`, some of which may not have had a chance to run `using Dagger` yet. Or is there a chance that the Chunk contains other Chunks which must be remote_fetched from other OSProcs?

**Comment by jpsamaroo** [comment]
Yes, please feel free to remove it from the `move` API (apparently I forgot to add it to the docstring too, so it was a late addition). You will have to bump the minor version since `move` is a semi-public API (used by DaggerGPU.jl, for example). If we need to add it back later, we can make it an optional argument added to the end of the `move()` call.

Side note: We also apparently serialize `ctx` in `do_task`, which I will need to fix later.

You make a great point, there doesn't seem to be any reason to serialize it in `collect_remote()`. Go ahead and just remove sending it at all.

**Comment by DrChainsaw** [comment]
Awesome! New commit coming soon.

**Comment by DrChainsaw** [comment]
Stupid markdown

**Comment by jpsamaroo** [comment]
Thanks a bunch!

**Pull request merged**
