### PR TITLE
Lowerbound to Julia 1.0 and add Project.toml

### PR DESCRIPTION
**Pull request by jpsamaroo**
Added Project.toml and excluded Manifest.toml in gitignore
Bumped Julia version to 1.0 in REQUIRE

Hopefully the `[compat]` line is correct too.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Any objections to what I've done here? We'll need a Project.toml if we're to register new versions in General, and this makes working with a `dev`'d Dagger project much easier to work with. So I'd like to get this PR in as soon as possible.

**Comment by aviks** [comment]
LGTM

**Comment by jpsamaroo** [comment]
Thanks! Would now be a good time to tag a minor/major release of Dagger?

**Comment by andreasnoack** [comment]
Yes. Please check that JuliaDB still works with these changes before making the release.

**Comment by jpsamaroo** [comment]
I already did a local run of the JuliaDB tests on Dagger master about a month ago, but I would like at least 1 more person to test that as well, just in case. I was hoping to recruit such a soul during the JuliaCon hackathon :)

**Pull request merged**
