### PR TITLE
Add Documenter docs

### LINKED ISSUE #103: Documentation/Examples?
Hi, is there someplace with  more documentation/examples/tutorials? Or is one required to read the source code?

### PR DESCRIPTION
**Pull request by jpsamaroo**
Closes #103 

Todo:
- [x] Setup CI to deploy docs
- [x] Add docs link to README
- [x] Move README docs to Documenter docs

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Would a Dagger admin be able to help me get these docs wired up in CI?

**Comment by DilumAluthge** [comment]
Bumping this.

@ViralBShah Do you know who is an owner of the JuliaParallel organization?

Alternatively, would it be possible to make @jpsamaroo an organization owner?

**Comment by ViralBShah** [comment]
Invited as owner.

**Comment by jpsamaroo** [comment]
So I merged this hastily to see where it would try to publish the docs to, but it seems like it's just publishing the old README to `https://juliaparallel.github.io/Dagger.jl/`, and the `gh-pages` branch was not created. Can anyone give me some hints on what to try?

**Comment by DilumAluthge** [comment]
Should be fixed by https://github.com/JuliaParallel/Dagger.jl/pull/131

**Pull request merged**
